version: '3.8'

services:
  db-accounts:
    image: mysql:8.0
    container_name: v-db-accounts
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: account_service_db
    ports:
      - "3306:3306"

  db-cards:
    image: mysql:8.0
    container_name: v-db-cards
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: card_service_db
    ports:
      - "3307:3306"

  redis:
    image: redis:7-alpine
    container_name: v-redis
    ports:
      - "6379:6379"
    # Cache getAccount no account-service: TTL 15 min (configurado em application.properties)

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    depends_on:
      - kafka
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # UI do Jaeger
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP