services:
  db-accounts:
    image: mysql:8.0
    container_name: v-db-accounts
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: account_service_db
    ports:
      - "3306:3306"

  db-cards:
    image: mysql:8.0
    container_name: v-db-cards
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: card_service_db
    ports:
      - "3307:3306"

  redis:
    image: redis:7-alpine
    container_name: v-redis
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0 # Versão fixa para evitar quebras
    container_name: v-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0 # Versão fixa compatível com Zookeeper
    container_name: v-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: v-kafdrop
    depends_on:
      - kafka
    ports:
      - "9099:9099"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
      JVM_OPTS: "-Xms32M -Xmx64M"

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: v-jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"